version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.4
        environment:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_CORE_DIR: /tmp/wordpress/
          PATH: $HOME/.composer/vendor/bin:$PATH
    steps:
      - checkout
      - run: apt-get update; apt-get install subversion
