version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8
        environment:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_CORE_DIR: /tmp/wordpress/
    steps:
      - run: echo 'export PATH=/$HOME/.composer/vendor/bin:$PATH' >> $BASH_ENV
      - checkout
      - run: sudo apt update && sudo apt install -y subversion
      - run: composer global require "phpunit/phpunit=5.7.*"
      - run: phpunit -v
