version: 2

jobs:
  build:
    docker:
      - image: circleci/php:5.6.22
        environment:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_CORE_DIR: /tmp/wordpress/
          PATH: $HOME/.composer/vendor/bin:$PATH

  steps:
    - checkout
    - run: sudo apt-get update; sudo apt-get install subversion
    - run: composer global require "phpunit/phpunit=5.7.*"
