version: 2

jobs:
  build:
    docker:
      - image: circleci/php:5.6
        environment:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_CORE_DIR: /tmp/wordpress/
      - image: circleci/php:7.0
        environment:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_CORE_DIR: /tmp/wordpress/
      - image: circleci/php:7.1
        environment:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_CORE_DIR: /tmp/wordpress/
    steps:
      - run: sudo apt-get update
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server
      - run: sudo apt install -y subversion mysql-workbench
      - run: echo 'export PATH=/$HOME/.composer/vendor/bin:$PATH' >> $BASH_ENV
      - checkout
      - run: composer global require "phpunit/phpunit=5.7.*"
      - run: |
          composer global require wp-coding-standards/wpcs
          phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
      - run: phpcs
      - run: |
          bash bin/install-wp-tests.sh wordpress_test ubuntu '' 127.0.0.1 latest
          phpunit
          WP_MULTISITE=1 phpunit
